---
- name: Deploy IoT Watchdog agent
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Create a directory named /usr/local/iot-watchdog
    file:
      path: /usr/local/iot-watchdog
      state: directory
      owner: root
      group: root
      mode: 0744
      recurse: yes

  - name: Copy watchdog agent code to target folder
    copy:
      src: "{{ source_code }}"
      dest: /usr/local/iot-watchdog
      owner: root
      group: root
      remote_src: False
      mode: 0744

  - name: Insert the IoT Watchdog agent UUID and force the registration
    blockinfile:
      path: /usr/local/iot-watchdog/config.cfg
      block: |
        iot_watchdog_agent_uuid={{ iot_watchdog_agent_uuid }}
        iot_watchdog_agent_need_registration={{ iot_watchdog_agent_need_registration }}
        mqtt_broker_certificate={{ iot_watchdog_mqtt_broker_certificate }}
      insertafter: EOF

  - name: Copy watchdog service definition
    copy:
      src: "{{ service_def }}"
      dest: /etc/systemd/system
      owner: root
      group: root
      remote_src: False
      mode: 0744

  - name: Insert MQTT broker hostname/ip into /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        {{ iot_watchdog_mqtt_broker_ip }} {{ iot_watchdog_mqtt_broker_hostname }}
      insertafter: EOF

  - name: Starting iot-watchdog service
    systemd:
      name: iot-watchdog.service
      state: started
      enabled: True